version: "3.9"

services:
  redis:
    image: redis

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - ".env"

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    depends_on:
      - redis
    env_file:
      - ".env"