version: "3.9"

services:
  redis:
    image: redis
    volumes:
      - redis_data:/data
    restart: unless-stopped

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - ".env"
    restart: unless-stopped

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    depends_on:
      - redis
    env_file:
      - ".env"
    restart: unless-stopped
    # For GPU support
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia

volumes:
  redis_data: